name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore ./Reference.Api/Reference.Api.csproj
    - name: Build
      run: dotnet build ./Reference.Api/Reference.Api.csproj
    
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          dotnet-version: '8.0.x'
      - name: Test
        run: dotnet test ./Reference.Api.Test/Reference.Api.Test.csproj
