# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Reference.Api/Reference.Api.csproj
    
      
  Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: dotnet test ./Reference.Api.Test/Reference.Api.Test.csproj
        
  update-readme:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add badge to README
        run: echo "<img alt='Build passing' src='https://img.shields.io/badge/Build-passing-brightgreen'>" >> ./README.md
