name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Reference.Api/Reference.Api.csproj
    
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: dotnet test ./Reference.Api.Test/Reference.Api.Test.csproj

  update-readme:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add badge to README
        run: echo "<img alt='Build passing' src='https://img.shields.io/badge/Build-passing-brightgreen'>" >> README.md
